name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        run: |
          echo "HOST=${{ secrets.SERVER_HOST }}"
          echo "USER=${{ secrets.SERVER_USERNAME }}"